;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	comint-delchar-or-maybe-eof
	company-indent-or-complete-common
	counsel-yank-pop
	delete-horizontal-space
	downcase-dwim
	forward-sexp
	kill-region
	kill-sexp
	magit-copy-buffer-revision
	magit-previous-line
	magit-section-backward
	markdown-outdent-or-delete
	mc-place-stop
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-emphasize
	org-end-of-line
	org-self-insert-command
	org-yank
	python-indent-dedent-line
	python-nav-forward-sexp-safe
	rjsx-delete-creates-full-tag
	rjsx-electric-gt
	rjsx-electric-lt
	sp-backward-kill-sexp
	sp-backward-sexp
	sp-backward-slurp-sexp
	sp-backward-up-sexp
	sp-copy-sexp
	sp-down-sexp
	sp-forward-sexp
	sp-kill-hybrid-sexp
	sp-remove-active-pair-overlay
	sp-slurp-hybrid-sexp
	upcase-char
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	yas-abort-snippet
	))

(setq mc/cmds-to-run-once
      '(
	ace-swap-window
	counsel-M-x
	counsel-grep-or-swiper
	mc-place
	prettier-js
	quit
	save-some-buffers
	sp-rewrap-sexp
	))
